### ISSUE TITLE
Criando Model com elementos de JSON

### ISSUE THREAD

**Issue by globsecure** [felipecsl/AsymmetricGridView#29]
Boa tarde Felipe,

Estou realizando alguns testes com sua lib, onde preciso usar o model "DemoItem" de um modo diferente.  Criando ele de um JSON com outros elementos além do "DemoItem" você tem algum exemplo básico disso?

Obrigado!

**Comment by felipecsl** [comment]
(sorry, replying in English since that's the default language used on Github)

You can have as much information as you want in your adapter items. It doesn't have to be a `DemoItem` either, the only requirement is that it implements the interface `AsymmetricItem`. You can use Gson, Jackson or any other JSON library, that has nothing to do with this library and it shouldn't interfere.

Please let me know if you need more info.
